databases:
  - name: rails-db
    databaseName: hyena_giraffe
    user: zookeeper
    plan: starter

services:
  - type: web
    name: rails-example
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec puma -t 5:5"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default